### ISSUE TITLE
Propose language of input to user

### ISSUE THREAD

**Issue by mikebarkmin** [mikebarkmin/lesbar.club#12]
When the user inputted a text, check the language of the text (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/detectLanguage) and then propose the detected language, if the currently selected language differs.

**Comment by neckenth** [comment]
@mikebarkmin I can take a look at this - can you assign to me?

**Comment by neckenth** [comment]
A few clarification questions for you:

The documentation you linked is to a Javascript API - is it cool if I use PyPi's [langdetect](https://pypi.org/project/langdetect/)?

Can I have a bit more detail as to what you're looking for here with regards UI/UX?

1. Are you thinking you want something like a modal to pop up with a language proposal, giving the user an opportunity to change the language to the detected one?
2. Do you want the language detection to happen after a certain number of characters has been typed or some number of seconds after a user has stopped typing?

**Comment by vingkan** [comment]
I just wanted to add two notes to this issue, my apologies if you were already aware of them:

1. The `detectLanguage` feature mentioned above is only available to browser extensions, so it may not be useful for the web application.
2. The [langdetect](https://github.com/Mimino666/langdetect) Python package provides a simple API for language detection, but it outputs ISO 639-1 language codes instead of ISO 3166-1 codes, which this project currently uses. Right now, that means that we would not be able to know if `"en"` means `"en_US"` or `"en_GB"`.

If I find a Python/JavaScript package that outputs ISO 3166-1 (with language and locale), I will share it here... but have not seen one yet.

You could also use location data to determine the locale, but that seems over the top. It might be better to just let the user choose the correct setting if there are multiple possible locales.

**Comment by mikebarkmin** [comment]
Thank you,

I was not aware, that detectLanguage only works in browser extensions. Bummer.

I have envisioned this feature as some kind of a fail safe for the user. Imagine your are checking a text and forgot the change the language to German. Then you would probably get very different result, because the dictionary which was used is for another language. Therefore the detection of syllables would be of. Also some metrics are also only suitable for some language.

So I guess it would be OK to detect the language, when the user sends the text to the back end. It could be just another key which will be added to the returning json. So using the langdetect python package is fine by me. 

Detecting if it is US or GB is very hard, I assume or even not possible for some texts. Therefore I suggest to just notify the user, if we detected that the detected language differs from the selected one.

There could be a little notification bar above the results div, which shows when the language differs. The content could be like: "Hey we detected a different language. Want to switch to {language}?". Of course we then have to define a default for example en_US.

Thank you both for your contributions to the issue.

**Comment by vingkan** [comment]
We could also use `langdetect` in its own API route so that the frontend can make a request to the backend to detect the language before the user submits. As @neckenth suggested, this could happen while the user is typing. If it happens while the user is typing, we could [debounce](https://blog.bitsrc.io/understanding-throttling-and-debouncing-973131c1ba07) the request to avoid harming the user interaction.

Either way, maybe the language detection should return a list of language codes that match. Currently this would only affect English: the `en` tag would yield `['en_US', 'en_GB']`. Maybe that would be too much, or maybe that would be important as support for more languages is added.

@neckenth let me know if you would like any assistance! On my branch, I have added a separate Flask route to request the detected language. But, the decision of how the user interaction will go is more important.

**Comment by neckenth** [comment]
@vingkan Sorry about the delay here

If you have already added the route, I think it's a fine way to go, though I'm wondering what you're thinking with regards user interaction there? Do you think the user should be notified while typing or as part of the result set as @mikebarkmin suggested?

I think if you want this to take place while the user is typing, we should definitely use your route, and I'm happy to pass this issue off to you. Otherwise, we probably don't need a new endpoint and we can just add the language as a property on the `Text` class and call `langdetect` from there. 

Let me know what you think.

**Comment by neckenth** [comment]
Just following up - @vingkan I was able to get the other method working (i.e. I was able to use add `detected_lang` as a property on the `Text` class and get the result to display in the results post-check.) 

Seems like both of us are half-way to complete solutions, so @mikebarkmin, which user interaction would you prefer?

**Comment by vingkan** [comment]
I like your solution a lot @neckenth! Seems to fit the user flow better than interrupting them while they are pasting or typing text.

**Comment by mikebarkmin** [comment]
Both solution seem quite nice, but I also think that the @neckenth is a bit better for the user flow. 

Maybe we could just calculate the metrics for the detected language as well (when the languages differ). Just in case the user really has forgotten to choose the right language. Then we could just replace the results without calling the backend again, when the user wants to use the detected one.

**Comment by neckenth** [comment]
Just passing along an update on this - I hope to be able to put up a PR within the next two days.

I was able to send two sets of results to the frontend - one for the selected language and one for the detected one.

I have some conditional rendering working to let the user know when the languages don't match and to show them a button to click to change their results to the detected language.

Next I will work on resetting the selected language displayed after a user clicks this new Change button.

I have a few outstanding questions:

1 - I'm not sure how to translate the readability metrics headings in the results into English.
2 - If I understand correctly, the readability metrics take language into account, so by changing the language and recalculating on the backend, the resulting numbers should be different. I'm not seeing them change as of right now, however. Are there any changes I have to make in order to properly make these calculations were the detected language to be English, for example?
3 - Should we plan to support just German and English for now?
4 - Can you add me as a collaborator so I can push up my branch to this repo?

**Comment by mikebarkmin** [comment]
Thanks for your commitment. You work will be great for the project. 

1 - Do not bother I will care for this
2 - You do not have to make any changes. I will display different metrics on the client. But all metrics will be calculated on the backend.  
3 - At the moment only German and English will be support. I do not know any metrics specific for other languages.
4 - I have done that

Thanks again :sunglasses:
